name: zuha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.0.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
#   fonts:
#     - family: DMSerifDisplay
#       fonts:
#         - asset: assets/fonts/DMSerifDisplay-Regular.ttf
#     - family: DMSans
#       fonts:
#         - asset: assets/fonts/DMSans-Regular.ttf
#           weight: 400
#         - asset: assets/fonts/DMSans-SemiBold.ttf
#           weight: 600
  uses-material-design: true
