// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDir5TqrL7Udr2ieqP4wZpaNGZDtpAYsE8',
    appId: '1:658614560737:web:7dbcd1111eaa817e28d4a0',
    messagingSenderId: '658614560737',
    projectId: 'zuha-43503',
    authDomain: 'zuha-43503.firebaseapp.com',
    storageBucket: 'zuha-43503.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfcx-7SL8Br-gkysdqP1_QP9wazigbeQ',
    appId: '1:658614560737:android:a3b873a6097c4afa28d4a0',
    messagingSenderId: '658614560737',
    projectId: 'zuha-43503',
    storageBucket: 'zuha-43503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5XqvZIQhmOq62Ja4nGM7eLLxePwKxVk',
    appId: '1:658614560737:ios:cbb24de74400f92d28d4a0',
    messagingSenderId: '658614560737',
    projectId: 'zuha-43503',
    storageBucket: 'zuha-43503.firebasestorage.app',
    iosBundleId: 'com.example.zuha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD5XqvZIQhmOq62Ja4nGM7eLLxePwKxVk',
    appId: '1:658614560737:ios:cbb24de74400f92d28d4a0',
    messagingSenderId: '658614560737',
    projectId: 'zuha-43503',
    storageBucket: 'zuha-43503.firebasestorage.app',
    iosBundleId: 'com.example.zuha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDir5TqrL7Udr2ieqP4wZpaNGZDtpAYsE8',
    appId: '1:658614560737:web:14afd45b7894301c28d4a0',
    messagingSenderId: '658614560737',
    projectId: 'zuha-43503',
    authDomain: 'zuha-43503.firebaseapp.com',
    storageBucket: 'zuha-43503.firebasestorage.app',
  );
}
